name: DemoApp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cente.png
    - assets/images/airtel.png
    - assets/images/mtn.png
    - assets/images/bill.png
    - assets/images/cash-withdrawal.png
    - assets/images/graduated.png
    - assets/images/lamp.png
    - assets/images/money.png
    - assets/images/send-money.png
    - assets/images/personal.png
    - assets/images/data.png
    - assets/images/hand.png
    - assets/images/payment-method.png
    - assets/images/express-delivery.png
    - assets/images/transaction-history.png
    - assets/images/appeals.png
    - assets/images/account.png
    - assets/images/th.png
    - assets/images/wlt.png




